name: sl_nic_bridge
description: "A Flutter application to streamline the Sri Lankan National Identity Card (NIC) application process."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management & Dependency Injection
  flutter_riverpod: ^2.4.9
  
  # Routing
  go_router: ^16.1.0
  
  # Networking
  dio: ^5.4.0
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Signature & Image Picker
  signature: ^6.3.0
  image_picker: ^1.0.4
  
  # App Info
  package_info_plus: ^8.3.1
  
  # JSON Annotation for serialization
  json_annotation: ^4.9.0
  
  # Intl for date formatting
  intl: ^0.20.2
  
  # Material Icons Extended
  material_symbols_icons: ^4.2719.3
  json_serializable: ^6.10.0
  build_runner: ^2.7.0
  file_picker: ^10.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/config/
    - assets/images/